parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(PG_APPLICATION_NAME): '{{ cookiecutter.name }}'

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                {% if 'post' in cookiecutter.db_mode %}
                driver: 'pdo_pgsql'
                server_version: '{{ cookiecutter.db_version }}'
                charset: utf8
                application_name: '%env(resolve:PG_APPLICATION_NAME)%'
                {% else %}
                driver: 'mysql'
                server_version: '{{ cookiecutter.db_version }}'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                {% endif %}
                url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: flase
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App:
