version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    environment: &{{cookiecutter.app_type}}_env
      SOMETHING: 1
      PHP_DISPLAY_ERROR: 1
      # NO_MIGRATE: "1"
      # NO_COLLECT_STATIC: "1"
      # NO_CACHE_CLEAR: "1"
      # NO_COMPOSER: "1"
    volumes: &symfony_volumes
      #- ./sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./sys/init.sh:/code/sys/init.sh
      #- ./sys/etc/supervisor.d:/code/etc/supervisor.d
      - ./local:/code/local
      - ./app:/code/app
{%- if not cookiecutter.no_private %}
      - ./private:/code/private
{%- endif%}
services:
  nginx:
    environment: {NO_SSL: ""}
    ports:
    - "8008:80"
  backup: {<<: [ *bypass ]}
  {%- if not cookiecutter.remove_cron %}
  cron: 
    build:
      context: "."
      args:
        PHP_VER: "${SYMFONY_PHP_VER:-7.2}"
    <<: [ *bypass ]
    <<: [ *{{cookiecutter.app_type}} ]
  {% endif %}
  {{cookiecutter.app_type}}:
    build:
      context: "."
      args:
        PHP_VER: "${SYMFONY_PHP_VER:-7.2}"
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: phpfpm
    ports:
      - "9000:9000"
  {{cookiecutter.app_type}}-fg:
    build:
      context: "."
      args:
        PHP_VER: "${SYMFONY_PHP_VER:-7.2}"
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: fg
    ports:
      - "8000:8000"
