version: '{{cookiecutter.compose_version}}'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args: &args
        BUILDKIT_INLINE_CACHE: "1"
        BASE: "${SYMFONY_BASE_IMAGE:-{{cookiecutter.base_image}}}"
        # BASE: "${DRUPAL_BASE_IMAGE:-{{cookiecutter.debian_image}}}"
        # BASE: "${DRUPAL_BASE_IMAGE:-{{cookiecutter.centos_image}}}"
        PHP_VER: "${PHP_VER:-{{cookiecutter.php_ver}}}"
        PHP_GROUP: "${PHP_GROUP-{{cookiecutter.php_group}}}"
        PHP_VER_NO_DOT: "${PHP_VER_NO_DOT:-{{cookiecutter.php_ver.replace('.', '') }}}"
        COMPOSER_VERSION: "${COMPOSER_VERSION:-{{cookiecutter.composer_ver}}}"
services:
{%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
{%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
{%- if cookiecutter.with_supervisor %}
  {{cookiecutter.app_type}}-supervisor: {<<: [ *{{cookiecutter.app_type}} ]}
{%-endif%}
  cypress:
    <<: [ *env ]
    image: cypress
    build: ./e2e
    volumes:
    - ./e2e/cypress:/app/cypress
    - ./e2e/cypress.json:/app/cypress.json
