version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    environment: &{{cookiecutter.app_type}}_env
      APP_ENV: "${APP_ENV-dev}"
      APP_SECRET: "${APP_SECRET-11111111111111111111111111111111}"
      PHP_DISPLAY_ERROR: "${PHP_DISPLAY_ERROR-1}"
      NO_MIGRATE: "${NO_MIGRATE-1}"
      NO_COLLECT_STATIC: "${NO_COLLECT_STATIC-1}"
      NO_CACHE_CLEAR: "${NO_CACHE_CLEAR-1}"
      NO_COMPOSER: "${NO_COMPOSER-1}"
      # Resolve Docker mac problems
      # NO_FIXPERMS: "1"
      # if you need to debug the docker init uncomment the next 2 lines
      # SDEBUG: "1"
      # NO_STARTUP_LOGS: ""
    volumes: &{{cookiecutter.app_type}}_volumes
    {%-if cookiecutter.use_submodule_for_deploy_code %}
      - ./local/symfony-deploy-common/sys/init.sh:/code/init/init.sh
      - ./local/symfony-deploy-common:/code/local/symfony-deploy-common
    {%- else%}
      - ./sys/init.sh:/code/init/init.sh
      - ./:/code/local/symfony-deploy-common
    {%- endif%}
      - ./sys:/code/sys
      - ./local:/code/local
      - ./app:/code/app
      # remount public/private (named volumes on prod, local remount on dev)
      # on /code/app/public/files and /code/app/private
      - ./app/public/files:/code/app/public/files
      - ./app/public/bundles:/code/app/public/bundles
      - ./app/private:/code/app/private
      - ./app/var/cache:/code/app/var/cache
      # For documentation as symfony can generate rst
      - ./docs:/code/app/docs
services:
  db:
    ports:
      - "${SYMFONY_DB_LISTEN:-0.0.0.0}:${SYMFONY_DB_PORT:-{{ cookiecutter.local_direct_db_port }}}:{{cookiecutter.db_port}}"
  nginx:
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      NO_SSL: "{%if not cookiecutter.ssl_in_dev%}1{%else%}0{%endif%}"
      NO_FORCE_SSL: "{%if not cookiecutter.ssl_in_dev%}1{%endif%}"
      NGINX_PORT: "${SYMFONY_HTTPS_PORT:-{{cookiecutter.local_http_port}}}"
      NGINX_SSL_PORT: "${SYMFONY_HTTPS_PORT:-{{cookiecutter.local_https_port}}}"
    ports:
      - "${SYMFONY_HTTP_LISTEN:-0.0.0.0}:${SYMFONY_HTTP_PORT:-{{cookiecutter.local_http_port}}}:${SYMFONY_HTTP_PORT:-{{cookiecutter.local_http_port}}}"
{%-if cookiecutter.ssl_in_dev %}
      - "${SYMFONY_HTTP_LISTEN:-0.0.0.0}:${SYMFONY_HTTPS_PORT:-{{cookiecutter.local_https_port}}}:${SYMFONY_HTTPS_PORT:-{{cookiecutter.local_https_port}}}"
{%- endif %}
    volumes:
      # remount public/private (named volumes on prod, local remount on dev)
      # on /code/app/public/files and /code/app/private
      - ./app/public/:/code/app/public
      - ./app/public/bundles:/code/app/public/bundles:ro
      - ./app/public/files:/code/app/public/files:ro
      - ./app/private:/code/app/private:ro
  backup: {<<: [ *bypass ]}
{%- if not cookiecutter.remove_cron %}
  cron:
    <<: [ *bypass, *{{cookiecutter.app_type}} ]
{%- endif %}
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: phpfpm
      PHP_XDEBUG_REMOTE: "${PHP_XDEBUG_REMOTE-1}"
      PHP_XDEBUG_IP: "${PHP_XDEBUG_IP-host.docker.internal}"
      PHP_XDEBUG_PORT: "${PHP_XDEBUG_PORT-9000}"
{%- if cookiecutter.with_supervisor %}
  {{cookiecutter.app_type}}-supervisor:
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: supervisor
      NO_MIGRATE: 1
      NO_COMPOSER: 1
      NO_COLLECT_STATIC: 1
{%-endif%}
