version: '3.7'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args:
        PHP_VER: "${SYMFONY_PHP_VER:-{{cookiecutter.php_ver}}}"
services:
  {%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
  {%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
  {{cookiecutter.app_type}}-fg: {<<: [ *{{cookiecutter.app_type}} ]}
