version: '{{cookiecutter.compose_version}}'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build: {context: ".", args: {BUILD_DEV: "y"}}
services:
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
{%- if cookiecutter.with_supervisor %}
  {{cookiecutter.app_type}}-supervisor: {<<: [ *{{cookiecutter.app_type}} ]}
{%-endif%}
{%- if not cookiecutter.remove_cron %}
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
{%- endif %}
