version: '3.7'
x-{{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
  image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
services:
  nginx:
    restart: unless-stopped
    ports:
    - "${SYMFONY_HTTP_LISTEN:-0.0.0.0}:${SYMFONY_HTTP_PORT:-80}:80"
    - "${SYMFONY_HTTP_LISTEN:-0.0.0.0}:${SYMFONY_HTTPS_PORT:-443}:443"
  {{cookiecutter.app_type}}:
    restart: unless-stopped
    <<: [ *{{cookiecutter.app_type}} ]
    ports:
    - "${SYMFONY_API_LISTEN:-127.0.0.1}:${SYMFONY_API_PORT:-9000}:9000"
{%- if cookiecutter.with_supervisor %}
  {{cookiecutter.app_type}}-supervisor:
    restart: unless-stopped
    <<: [ *{{cookiecutter.app_type}} ]
{%-endif%}
{%- if not cookiecutter.remove_cron %}
  cron:
    restart: unless-stopped
{%- endif%}
  backup:
    restart: unless-stopped
  mailcatcher:
    restart: unless-stopped
{%-if cookiecutter.with_redis%}
  redis:
    restart: unless-stopped
{%-endif%}
  db:
    restart: unless-stopped
{%- if cookiecutter.db_mode.startswith('post') %}
  setup-postgres:
{%- elif cookiecutter.db_mode.startswith('m') %}
  setup-mysql:
    restart: unless-stopped
{%- endif %}
