version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    environment: &{{cookiecutter.app_type}}_env
       # NO_MIGRATE: "1"
       # NO_COLLECT_STATIC: "1"
       # NO_CACHE_CLEAR: "1"
       # NO_COMPOSER: "1"
    volumes: &symfony_volumes
      #- ./sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./sys/init.sh:/code/sys/init.sh
      #- ./sys/etc/supervisor.d:/code/etc/supervisor.d
      - ./local:/code/local
      - ./app:/code/app
{%- if not cookiecutter.no_private %}
      - ./private:/code/private
{%- endif%}
services:
  nginx: {<<: [ *bypass ]}
  # uncomment to activate in dev
  # nginx:
  # environment: {NO_SSL: ""}
  # ports:
  #   - 80: 80
  #   - 443: 443
  backup: {<<: [ *bypass ]}
  cron: 
    build:
      context: "."
      args:
        PHP_VER: "${SYMFONY_PHP_VER:-7.2}"
    <<: [ *bypass ]
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: fg
    ports:
      - "8000:8000"
