version: '3.7'
x-{{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
  image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
services:
  nginx:
    ports:
    - 80:80
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
    ports:
    - "9000:9000"
  {% if not cookiecutter.remove_cron %}
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
  {%- endif%}
